"""Feat: Added album column

Revision ID: 86d16c8859e4
Revises: 2bb5e4d53495
Create Date: 2023-03-13 11:24:52.214672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d16c8859e4'
down_revision = '2bb5e4d53495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('album')

    # ### end Alembic commands ###
