"""Feat: remved the liked

Revision ID: ef85946147a6
Revises: dcabcef40db2
Create Date: 2023-03-13 13:46:02.558579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef85946147a6'
down_revision = 'dcabcef40db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('liked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
